version: '3'

services:
  nest-app:
    build:
      context: .
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - redis
    env_file:
      - .env

  postgres:
    image: "postgres:latest"
    container_name: "nest-postgres"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

  redis:
    image: "redis:latest"
    container_name: "nest-redis"
    ports:
      - "6379:6379"